# Nixpacks configuration for Railway deployment
[phases.setup]
pkgs = ["python312", "python312Packages.pip"]

[phases.install]
cmds = [
  "cd backend",
  "pip3 install -r requirements.txt"
]

[phases.build]
cmds = [
  "cd backend",
  "python3 -c 'import chordme; print(\"Backend validation successful\")'"
]

[start]
cmd = "cd backend && python3 run.py"

[variables]
PORT = "5000"
PYTHONPATH = "."
