# Render deployment configuration for ChordMe backend
services:
  - type: web
    name: chordme-backend
    env: python
    region: frankfurt  # or oregon, singapore, etc.
    buildCommand: |
      cd backend
      pip install -r requirements.txt
    startCommand: |
      cd backend
      python run.py
    healthCheckPath: /api/v1/health
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: chordme-db
          property: connectionString
      - key: FLASK_ENV
        value: production
      - key: FLASK_CONFIG
        value: config
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1

# Database configuration (PostgreSQL)
databases:
  - name: chordme-db
    databaseName: chordme
    user: chordme_user
    region: frankfurt  # should match the web service region