apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: chordme
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: chordme-backend:latest
        imagePullPolicy: Never  # Use local images for Minikube
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          valueFrom:
            configMapKeyRef:
              name: chordme-config
              key: FLASK_ENV
        - name: FLASK_DEBUG
          valueFrom:
            configMapKeyRef:
              name: chordme-config
              key: FLASK_DEBUG
        - name: HTTPS_ENFORCED
          valueFrom:
            configMapKeyRef:
              name: chordme-config
              key: HTTPS_ENFORCED
        - name: DATABASE_URL
          value: "postgresql://postgres:$(POSTGRES_PASSWORD)@postgres-service:5432/chordme"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: chordme-secrets
              key: postgres-password
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: chordme-secrets
              key: jwt-secret-key
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: chordme-secrets
              key: secret-key
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 5000
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: chordme
spec:
  selector:
    app: backend
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP