title: ChordMe User Manual
description: Comprehensive documentation for ChordMe - Lyrics and chords in a simple way
theme: minima
show_downloads: true
github:
  repository_url: https://github.com/tonybolanyo/chordme
  
plugins:
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

exclude:
  - vendor/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - "*.gemspec"

include:
  - .nojekyll

# Multi-language configuration
languages: ["en", "es"]
default_lang: "en"

# Main navigation sections
header_pages:
  # User Documentation
  - getting-started.md
  - user-guide.md
  - chordpro-format.md
  - troubleshooting.md
  # Developer Documentation  
  - developer-guide.md
  - api-reference.md
  - api-documentation.md
  - testing.md
  # Infrastructure & Deployment
  - infrastructure.md
  - deployment.md
  - deployment-netlify-railway-supabase.md
  # Security & Compliance
  - security-checklist.md
  - threat-model.md
  - final-security-audit-report.md
  # Collaboration Features
  - collaborative-editing-architecture.md
  - firebase-integration.md
  - google-oauth-integration.md
  # Testing & Quality
  - collaboration-test-coverage-report.md
  - codecov.md
  # Project Information
  - changelog.md
  - workflows-documentation.md

header_pages_es:
  # User Documentation
  - getting-started-es.md
  - user-guide-es.md
  - chordpro-format-es.md
  - troubleshooting-es.md
  # Developer Documentation
  - developer-guide-es.md
  - api-reference-es.md
  - api-documentation-es.md
  - testing-es.md
  # Infrastructure & Deployment
  - infrastructure-es.md
  - deployment-es.md
  - deployment-netlify-railway-supabase-es.md
  # Security & Compliance
  - security-checklist-es.md
  - threat-model-es.md
  - final-security-audit-report-es.md
  # Collaboration Features
  - collaborative-editing-architecture-es.md
  - firebase-integration-es.md
  - google-oauth-integration-es.md
  # Testing & Quality
  - collaboration-test-coverage-report-es.md
  - codecov-es.md
  # Project Information
  - changelog-es.md
  - workflows-documentation-es.md

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  # Spanish language defaults
  - scope:
      path: "*-es.md"
    values:
      lang: "es"
  - scope:
      path: "index-es.md"
    values:
      lang: "es"

